version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chat-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_service
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerasdf
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: chat-service-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data: